### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#123]
Thanks for an excellent plugin! :boat: 

It would be great if your plugin would work with Bitcode. Bitcode is opt-out in iOS 9, and will be mandatory in the future.

Also, disabling it via Cordova is quite painful, so not having to would be nice.

[More on Bitcode, from Apple Docs](https://developer.apple.com/library/prerelease/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)

**Comment by shaders** [comment]
Should be supported now (actually 3 days ago).

**Comment by shaders** [comment]
P.S. not available for PGB yet since 
http://community.phonegap.com/nitobi/topics/phonegap-build-fails-how-to-add-google-play-servies

**Comment by zarko-tg** [comment]
@shaders Can you confirm that this is the actual change introduced for Bitcode support? https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/d184f5e66f37d37f533aee4ad041a7a162977945
It was not obvious from the commit description.

Thank you

**Comment by shaders** [comment]
Yes

**Comment by btafel** [comment]
For some reason after upgrading to Xcode 7.0.1 this week, app won't build again, throwing this error

ld: bitcode bundle could not be generated because '/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh(PWNotification.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

I'm forced to build without bircode support. I tried removing and adding the plugin, but no luck. Any ideas?

**Comment by shaders** [comment]
@btafel Could you please confirm the plugin version do you use? Also please see my comments on https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/issues/132 issue.

It would be great to know the Pushwoosh library file size.

**Comment by shaders** [comment]
P.S. This is fixed in 
https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/91ba31e11c229e9367a45d5f475787521135683d
