### ISSUE TITLE
registerDevice doesn't always take effect

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#135]
We have been experiencing a problem with device registration for a while already (in terms of months or ever since i've started using the plugin). This applies to both iOS and Android and it also seems not to depend on push gateway type (production or sandboxed).
Currently on pushwoosh-cordova-plugin 3.6.11

Given a Cordova Ionic application that supports a particular user session with login and logout functionality, we register the device for push on login and unregister from push on logout.
From a PushWoosh plugin API perspective, both calls always succeed as expected.

The problem is that sometimes the devices are actually not registered for push with the corresponding gateway (they cannot receive push notifications). Despite the fact that registerDevice returns successfully.

Please investigate this issue as it gives a bad experience for the user given that it isn't predictable when it happens.

**Comment by shaders** [comment]
Do you know when did it happen last time?

**Comment by zarko-tg** [comment]
Like about an hour ago.
I cannot find a pattern really but I easily end up reproducing the issue after couple of rounds of registration and unregistration.

**Comment by vik-buchinski** [comment]
I just caught the same bug. Executed registerDevice success callback with token, but device is not registered on server(in pushwoosh admin console) plugin version: 3.6.14. OS: Android
How repeat it:
1. Install(delete previous version before install) app.
2. Open installed app and execute functions in next queue:
a. unregisterDevice after success callback or error callback fired go to step 'b'
b. registerDevice
(after this steps all is ok, and pushwoosh plugin works as expected)
3. download new version of app and install it
4. Open installed app and execute functions in next queue:
a. unregisterDevice after success callback or error callback fired go to step b (after this function pushwoosh console displaying, that device is not subscribed on push notifications anymore)
b. registerDevice
Register device executing success callback with token, but pushwoosh admin console is not displaying, that device registered, and device can not receive push notifications.
Please fix it ASAP, because it is critical bug for me =\....

**Comment by zarko-tg** [comment]
@shaders please have a look at his case, it is the most severe we have experienced with the otherwise great plugin and service.

I created a small test app to use when reproducing. it can be downloaded here: http://1drv.ms/1MEKzsf
Once unpacked, run the following commands in the root folder of the app:
```
$ cordova platform add android
$ cordova plugin add pushwoosh-cordova-plugin
$ cordova build
$ cordova run (you need a connected Android phone)
```

The problem can be seen in the following manner:
1. Tap on the "Register button". Take note of the token printed on the debug console.
2. Create a push message targeting the device with the token. It will be received and shown.
3. Tap on the "Unregister" button.
4. Kill and the start the app again.
5. Repeat steps 1 and 2

At this point it is no longer possible to receive push notifications.

**Comment by vik-buchinski** [comment]
@zarko-tg Try to change pugin version to 
<gap:plugin name="pushwoosh-pgb-plugin" source="npm" version="3.6.14" />
Is here the same behaviour?

**Comment by zarko-tg** [comment]
@vik-buchinski Using the latest plugin version over here. The problem is unrelated to any (recent) version as it seems it has been present for a while.

**Comment by shaders** [comment]
Checking this.

**Comment by shaders** [comment]
I confirm this behavior. Let me speak with the team.

**Comment by shaders** [comment]
Got the update from the team. Let me explain.

First of all I can agree this is "sort of" a bug, however the system was not designed to be used in that way. Basically when you unregister device it takes about a minute to purge all the caches. Therefore the next minute you try to register device - it won't.

What you have to do is to create (for example) "subscribed" flag and set/unset it instead of registering/unregistering device. Then use simple filter by this flag to send push notifications to.

Said that though I've got this issue entered as a bug so it will be fixed soon!
Meanwhile I'm closing the issue.

**Comment by zarko-tg** [comment]
Thanks for the explanation @shaders.
The suggested workaround kinda defeats the purpose of unregisterDevice. I think we'll wait for a proper fix on your backend.

**Comment by shaders** [comment]
I agree, it's scheduled to be fixed during this sprint.

**Comment by shaders** [comment]
And it has been fixed! Closing the issue.

**Comment by zarko-tg** [comment]
I'll be testing.
Thank you and woosh ftw!

**Comment by zarko-tg** [comment]
Initial tests show the problem is resolved.
